# Generated by Django 5.2.13 on 2026-04-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('it', 'Italiano')], default='en', max_length=8),
        ),
    ]
