# Generated by Django 5.2.13 on 2026-04-17 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('link', 'Link'), ('text', 'Text'), ('file', 'File')], max_length=8)),
                ('title', models.TextField()),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('content_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['task'], name='attachments_task_id_5eb67e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'link'), ('url__isnull', False)), models.Q(('content__isnull', False), ('kind', 'text')), models.Q(('content_type__isnull', False), ('file__isnull', False), ('kind', 'file')), _connector='OR'), name='attachment_kind_fields_match')],
            },
        ),
    ]
