# Generated by Django 5.2.13 on 2026-04-17 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('agent_type', models.CharField(blank=True, max_length=64)),
                ('agent_name', models.CharField(blank=True, max_length=128)),
                ('agent_session_id', models.CharField(blank=True, max_length=128)),
                ('terminal_session_id', models.CharField(blank=True, max_length=128)),
                ('branch_name', models.TextField(blank=True)),
                ('worktree_path', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('pr_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.board')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='boards.column')),
            ],
            options={
                'ordering': ('sort_order', 'created_at'),
                'indexes': [models.Index(fields=['column'], name='tasks_task_column__b027ef_idx'), models.Index(fields=['board'], name='tasks_task_board_i_f0b4cf_idx')],
            },
        ),
    ]
