/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PublicRouteImport } from "./routes/_public"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as AuthenticatedIndexRouteImport } from "./routes/_authenticated/index"
import { Route as PublicVerifySuccessRouteImport } from "./routes/_public/verify-success"
import { Route as PublicRegisterRouteImport } from "./routes/_public/register"
import { Route as PublicRecoverRouteImport } from "./routes/_public/recover"
import { Route as PublicLoginRouteImport } from "./routes/_public/login"
import { Route as PublicFaultPreviewRouteImport } from "./routes/_public/fault-preview"
import { Route as PublicCheckEmailRouteImport } from "./routes/_public/check-email"
import { Route as PublicRecoverIndexRouteImport } from "./routes/_public/recover.index"
import { Route as AuthenticatedSettingsIndexRouteImport } from "./routes/_authenticated/settings/index"
import { Route as PublicRecoverConfirmRouteImport } from "./routes/_public/recover.confirm"

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicVerifySuccessRoute = PublicVerifySuccessRouteImport.update({
  id: "/verify-success",
  path: "/verify-success",
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => PublicRoute,
} as any)
const PublicRecoverRoute = PublicRecoverRouteImport.update({
  id: "/recover",
  path: "/recover",
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaultPreviewRoute = PublicFaultPreviewRouteImport.update({
  id: "/fault-preview",
  path: "/fault-preview",
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckEmailRoute = PublicCheckEmailRouteImport.update({
  id: "/check-email",
  path: "/check-email",
  getParentRoute: () => PublicRoute,
} as any)
const PublicRecoverIndexRoute = PublicRecoverIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => PublicRecoverRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PublicRecoverConfirmRoute = PublicRecoverConfirmRouteImport.update({
  id: "/confirm",
  path: "/confirm",
  getParentRoute: () => PublicRecoverRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AuthenticatedIndexRoute
  "/check-email": typeof PublicCheckEmailRoute
  "/fault-preview": typeof PublicFaultPreviewRoute
  "/login": typeof PublicLoginRoute
  "/recover": typeof PublicRecoverRouteWithChildren
  "/register": typeof PublicRegisterRoute
  "/verify-success": typeof PublicVerifySuccessRoute
  "/recover/confirm": typeof PublicRecoverConfirmRoute
  "/settings/": typeof AuthenticatedSettingsIndexRoute
  "/recover/": typeof PublicRecoverIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof AuthenticatedIndexRoute
  "/check-email": typeof PublicCheckEmailRoute
  "/fault-preview": typeof PublicFaultPreviewRoute
  "/login": typeof PublicLoginRoute
  "/register": typeof PublicRegisterRoute
  "/verify-success": typeof PublicVerifySuccessRoute
  "/recover/confirm": typeof PublicRecoverConfirmRoute
  "/settings": typeof AuthenticatedSettingsIndexRoute
  "/recover": typeof PublicRecoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/_public": typeof PublicRouteWithChildren
  "/_public/check-email": typeof PublicCheckEmailRoute
  "/_public/fault-preview": typeof PublicFaultPreviewRoute
  "/_public/login": typeof PublicLoginRoute
  "/_public/recover": typeof PublicRecoverRouteWithChildren
  "/_public/register": typeof PublicRegisterRoute
  "/_public/verify-success": typeof PublicVerifySuccessRoute
  "/_authenticated/": typeof AuthenticatedIndexRoute
  "/_public/recover/confirm": typeof PublicRecoverConfirmRoute
  "/_authenticated/settings/": typeof AuthenticatedSettingsIndexRoute
  "/_public/recover/": typeof PublicRecoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/check-email"
    | "/fault-preview"
    | "/login"
    | "/recover"
    | "/register"
    | "/verify-success"
    | "/recover/confirm"
    | "/settings/"
    | "/recover/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/check-email"
    | "/fault-preview"
    | "/login"
    | "/register"
    | "/verify-success"
    | "/recover/confirm"
    | "/settings"
    | "/recover"
  id:
    | "__root__"
    | "/_authenticated"
    | "/_public"
    | "/_public/check-email"
    | "/_public/fault-preview"
    | "/_public/login"
    | "/_public/recover"
    | "/_public/register"
    | "/_public/verify-success"
    | "/_authenticated/"
    | "/_public/recover/confirm"
    | "/_authenticated/settings/"
    | "/_public/recover/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated/": {
      id: "/_authenticated/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_public/verify-success": {
      id: "/_public/verify-success"
      path: "/verify-success"
      fullPath: "/verify-success"
      preLoaderRoute: typeof PublicVerifySuccessRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/register": {
      id: "/_public/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/recover": {
      id: "/_public/recover"
      path: "/recover"
      fullPath: "/recover"
      preLoaderRoute: typeof PublicRecoverRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/login": {
      id: "/_public/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/fault-preview": {
      id: "/_public/fault-preview"
      path: "/fault-preview"
      fullPath: "/fault-preview"
      preLoaderRoute: typeof PublicFaultPreviewRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/check-email": {
      id: "/_public/check-email"
      path: "/check-email"
      fullPath: "/check-email"
      preLoaderRoute: typeof PublicCheckEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/recover/": {
      id: "/_public/recover/"
      path: "/"
      fullPath: "/recover/"
      preLoaderRoute: typeof PublicRecoverIndexRouteImport
      parentRoute: typeof PublicRecoverRoute
    }
    "/_authenticated/settings/": {
      id: "/_authenticated/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_public/recover/confirm": {
      id: "/_public/recover/confirm"
      path: "/confirm"
      fullPath: "/recover/confirm"
      preLoaderRoute: typeof PublicRecoverConfirmRouteImport
      parentRoute: typeof PublicRecoverRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRecoverRouteChildren {
  PublicRecoverConfirmRoute: typeof PublicRecoverConfirmRoute
  PublicRecoverIndexRoute: typeof PublicRecoverIndexRoute
}

const PublicRecoverRouteChildren: PublicRecoverRouteChildren = {
  PublicRecoverConfirmRoute: PublicRecoverConfirmRoute,
  PublicRecoverIndexRoute: PublicRecoverIndexRoute,
}

const PublicRecoverRouteWithChildren = PublicRecoverRoute._addFileChildren(
  PublicRecoverRouteChildren,
)

interface PublicRouteChildren {
  PublicCheckEmailRoute: typeof PublicCheckEmailRoute
  PublicFaultPreviewRoute: typeof PublicFaultPreviewRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRecoverRoute: typeof PublicRecoverRouteWithChildren
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicVerifySuccessRoute: typeof PublicVerifySuccessRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCheckEmailRoute: PublicCheckEmailRoute,
  PublicFaultPreviewRoute: PublicFaultPreviewRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRecoverRoute: PublicRecoverRouteWithChildren,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicVerifySuccessRoute: PublicVerifySuccessRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
