/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as PublicRouteImport } from "./routes/_public"
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PublicVerifySuccessRouteImport } from "./routes/_public/verify-success"
import { Route as PublicRegisterRouteImport } from "./routes/_public/register"
import { Route as PublicLoginRouteImport } from "./routes/_public/login"
import { Route as PublicCheckEmailRouteImport } from "./routes/_public/check-email"
import { Route as AuthenticatedTerminalIndexRouteImport } from "./routes/_authenticated/terminal/index"
import { Route as AuthenticatedSettingsIndexRouteImport } from "./routes/_authenticated/settings/index"
import { Route as AuthenticatedKanbanIndexRouteImport } from "./routes/_authenticated/kanban/index"
import { Route as AuthenticatedGitIndexRouteImport } from "./routes/_authenticated/git/index"
import { Route as AuthenticatedTerminalSettingsRouteImport } from "./routes/_authenticated/terminal/settings"
import { Route as AuthenticatedKanbanSettingsRouteImport } from "./routes/_authenticated/kanban/settings"
import { Route as AuthenticatedKanbanListRouteImport } from "./routes/_authenticated/kanban/list"
import { Route as AuthenticatedKanbanAgentsRouteImport } from "./routes/_authenticated/kanban/agents"

const PublicRoute = PublicRouteImport.update({
  id: "/_public",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifySuccessRoute = PublicVerifySuccessRouteImport.update({
  id: "/verify-success",
  path: "/verify-success",
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckEmailRoute = PublicCheckEmailRouteImport.update({
  id: "/check-email",
  path: "/check-email",
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedTerminalIndexRoute =
  AuthenticatedTerminalIndexRouteImport.update({
    id: "/terminal/",
    path: "/terminal/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: "/settings/",
    path: "/settings/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKanbanIndexRoute =
  AuthenticatedKanbanIndexRouteImport.update({
    id: "/kanban/",
    path: "/kanban/",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGitIndexRoute = AuthenticatedGitIndexRouteImport.update({
  id: "/git/",
  path: "/git/",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTerminalSettingsRoute =
  AuthenticatedTerminalSettingsRouteImport.update({
    id: "/terminal/settings",
    path: "/terminal/settings",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKanbanSettingsRoute =
  AuthenticatedKanbanSettingsRouteImport.update({
    id: "/kanban/settings",
    path: "/kanban/settings",
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedKanbanListRoute = AuthenticatedKanbanListRouteImport.update({
  id: "/kanban/list",
  path: "/kanban/list",
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKanbanAgentsRoute =
  AuthenticatedKanbanAgentsRouteImport.update({
    id: "/kanban/agents",
    path: "/kanban/agents",
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/check-email": typeof PublicCheckEmailRoute
  "/login": typeof PublicLoginRoute
  "/register": typeof PublicRegisterRoute
  "/verify-success": typeof PublicVerifySuccessRoute
  "/kanban/agents": typeof AuthenticatedKanbanAgentsRoute
  "/kanban/list": typeof AuthenticatedKanbanListRoute
  "/kanban/settings": typeof AuthenticatedKanbanSettingsRoute
  "/terminal/settings": typeof AuthenticatedTerminalSettingsRoute
  "/git/": typeof AuthenticatedGitIndexRoute
  "/kanban/": typeof AuthenticatedKanbanIndexRoute
  "/settings/": typeof AuthenticatedSettingsIndexRoute
  "/terminal/": typeof AuthenticatedTerminalIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/check-email": typeof PublicCheckEmailRoute
  "/login": typeof PublicLoginRoute
  "/register": typeof PublicRegisterRoute
  "/verify-success": typeof PublicVerifySuccessRoute
  "/kanban/agents": typeof AuthenticatedKanbanAgentsRoute
  "/kanban/list": typeof AuthenticatedKanbanListRoute
  "/kanban/settings": typeof AuthenticatedKanbanSettingsRoute
  "/terminal/settings": typeof AuthenticatedTerminalSettingsRoute
  "/git": typeof AuthenticatedGitIndexRoute
  "/kanban": typeof AuthenticatedKanbanIndexRoute
  "/settings": typeof AuthenticatedSettingsIndexRoute
  "/terminal": typeof AuthenticatedTerminalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authenticated": typeof AuthenticatedRouteWithChildren
  "/_public": typeof PublicRouteWithChildren
  "/_public/check-email": typeof PublicCheckEmailRoute
  "/_public/login": typeof PublicLoginRoute
  "/_public/register": typeof PublicRegisterRoute
  "/_public/verify-success": typeof PublicVerifySuccessRoute
  "/_authenticated/kanban/agents": typeof AuthenticatedKanbanAgentsRoute
  "/_authenticated/kanban/list": typeof AuthenticatedKanbanListRoute
  "/_authenticated/kanban/settings": typeof AuthenticatedKanbanSettingsRoute
  "/_authenticated/terminal/settings": typeof AuthenticatedTerminalSettingsRoute
  "/_authenticated/git/": typeof AuthenticatedGitIndexRoute
  "/_authenticated/kanban/": typeof AuthenticatedKanbanIndexRoute
  "/_authenticated/settings/": typeof AuthenticatedSettingsIndexRoute
  "/_authenticated/terminal/": typeof AuthenticatedTerminalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/check-email"
    | "/login"
    | "/register"
    | "/verify-success"
    | "/kanban/agents"
    | "/kanban/list"
    | "/kanban/settings"
    | "/terminal/settings"
    | "/git/"
    | "/kanban/"
    | "/settings/"
    | "/terminal/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/check-email"
    | "/login"
    | "/register"
    | "/verify-success"
    | "/kanban/agents"
    | "/kanban/list"
    | "/kanban/settings"
    | "/terminal/settings"
    | "/git"
    | "/kanban"
    | "/settings"
    | "/terminal"
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_public"
    | "/_public/check-email"
    | "/_public/login"
    | "/_public/register"
    | "/_public/verify-success"
    | "/_authenticated/kanban/agents"
    | "/_authenticated/kanban/list"
    | "/_authenticated/kanban/settings"
    | "/_authenticated/terminal/settings"
    | "/_authenticated/git/"
    | "/_authenticated/kanban/"
    | "/_authenticated/settings/"
    | "/_authenticated/terminal/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_public": {
      id: "/_public"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authenticated": {
      id: "/_authenticated"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_public/verify-success": {
      id: "/_public/verify-success"
      path: "/verify-success"
      fullPath: "/verify-success"
      preLoaderRoute: typeof PublicVerifySuccessRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/register": {
      id: "/_public/register"
      path: "/register"
      fullPath: "/register"
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/login": {
      id: "/_public/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_public/check-email": {
      id: "/_public/check-email"
      path: "/check-email"
      fullPath: "/check-email"
      preLoaderRoute: typeof PublicCheckEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    "/_authenticated/terminal/": {
      id: "/_authenticated/terminal/"
      path: "/terminal"
      fullPath: "/terminal/"
      preLoaderRoute: typeof AuthenticatedTerminalIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/settings/": {
      id: "/_authenticated/settings/"
      path: "/settings"
      fullPath: "/settings/"
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/kanban/": {
      id: "/_authenticated/kanban/"
      path: "/kanban"
      fullPath: "/kanban/"
      preLoaderRoute: typeof AuthenticatedKanbanIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/git/": {
      id: "/_authenticated/git/"
      path: "/git"
      fullPath: "/git/"
      preLoaderRoute: typeof AuthenticatedGitIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/terminal/settings": {
      id: "/_authenticated/terminal/settings"
      path: "/terminal/settings"
      fullPath: "/terminal/settings"
      preLoaderRoute: typeof AuthenticatedTerminalSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/kanban/settings": {
      id: "/_authenticated/kanban/settings"
      path: "/kanban/settings"
      fullPath: "/kanban/settings"
      preLoaderRoute: typeof AuthenticatedKanbanSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/kanban/list": {
      id: "/_authenticated/kanban/list"
      path: "/kanban/list"
      fullPath: "/kanban/list"
      preLoaderRoute: typeof AuthenticatedKanbanListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    "/_authenticated/kanban/agents": {
      id: "/_authenticated/kanban/agents"
      path: "/kanban/agents"
      fullPath: "/kanban/agents"
      preLoaderRoute: typeof AuthenticatedKanbanAgentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedKanbanAgentsRoute: typeof AuthenticatedKanbanAgentsRoute
  AuthenticatedKanbanListRoute: typeof AuthenticatedKanbanListRoute
  AuthenticatedKanbanSettingsRoute: typeof AuthenticatedKanbanSettingsRoute
  AuthenticatedTerminalSettingsRoute: typeof AuthenticatedTerminalSettingsRoute
  AuthenticatedGitIndexRoute: typeof AuthenticatedGitIndexRoute
  AuthenticatedKanbanIndexRoute: typeof AuthenticatedKanbanIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTerminalIndexRoute: typeof AuthenticatedTerminalIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedKanbanAgentsRoute: AuthenticatedKanbanAgentsRoute,
  AuthenticatedKanbanListRoute: AuthenticatedKanbanListRoute,
  AuthenticatedKanbanSettingsRoute: AuthenticatedKanbanSettingsRoute,
  AuthenticatedTerminalSettingsRoute: AuthenticatedTerminalSettingsRoute,
  AuthenticatedGitIndexRoute: AuthenticatedGitIndexRoute,
  AuthenticatedKanbanIndexRoute: AuthenticatedKanbanIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTerminalIndexRoute: AuthenticatedTerminalIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicCheckEmailRoute: typeof PublicCheckEmailRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicVerifySuccessRoute: typeof PublicVerifySuccessRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCheckEmailRoute: PublicCheckEmailRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicVerifySuccessRoute: PublicVerifySuccessRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
